import { IVideo } from "../types";

export const mockVideo: IVideo[] = [
  {
    id: "1",
    title: "Introduction to Marine Biology",
    videoType: "Video File",
    group: "Documentaries",
    uploadedDate: "2023-10-12",
    lastUpdated: "2023-10-15",
    uploadedBy: "lady@bug.com",
    thumbnailUrl:
      "https://img.freepik.com/free-vector/internet-communication_24877-51945.jpg?semt=ais_hybrid",
    isProcessing: false,
    tags: ["marine", "biology", "ocean"],
  },
  {
    id: "2",
    title: "Live Stream: Space Exploration 2024",
    videoType: "Live Stream",
    group: "Science",
    uploadedDate: "2024-01-05",
    lastUpdated: "2024-01-06",
    uploadedBy: "lady@bug.com",
    isProcessing: true,
    tags: ["space", "exploration", "2024"],
    thumbnailUrl:
      "https://marketing4ecommerce.net/en/wp-content/uploads/sites/8/2024/04/internet.jpg",
  },
  {
    id: "3",
    title: "Recording: Quantum Physics Explained",
    videoType: "Recording",
    group: "Education",
    uploadedDate: "2023-09-20",
    lastUpdated: "2023-09-22",
    uploadedBy: "Dr. John Doe",
    thumbnailUrl: "",
    isProcessing: false,
    tags: ["quantum", "physics", "science"],
  },
  {
    id: "4",
    title: "Mountain Adventure: Climbing the Rockies",
    videoType: "Video File",
    group: "Travel",
    uploadedDate: "2023-11-10",
    lastUpdated: "2023-11-11",
    uploadedBy: "lady@bug.com",
    thumbnailUrl: "",
    isProcessing: false,
    tags: ["mountain", "adventure", "travel"],
  },
  {
    id: "5",
    title: "Live Stream: Coding Bootcamp Day 1",
    videoType: "Live Stream",
    group: "Education",
    uploadedDate: "2024-01-10",
    lastUpdated: "2024-01-10",
    uploadedBy: "Tech Academy",
    thumbnailUrl: "",
    isProcessing: true,
    tags: ["coding", "bootcamp", "live"],
  },
  {
    id: "6",
    title: "Cooking 101: Basics of Italian Cuisine",
    videoType: "Video File",
    group: "Cooking",
    uploadedDate: "2023-08-15",
    lastUpdated: "2023-08-18",
    uploadedBy: "Chef Luigi",
    thumbnailUrl: "",
    isProcessing: false,
    tags: ["cooking", "italian", "food"],
  },
  {
    id: "7",
    title: "Recording: Artificial Intelligence Overview",
    videoType: "Recording",
    group: "Technology",
    uploadedDate: "2023-07-20",
    lastUpdated: "2023-07-22",
    uploadedBy: "Tech Insights",
    thumbnailUrl: "",
    isProcessing: false,
    tags: ["AI", "technology", "future"],
  },
  {
    id: "8",
    title: "Travel Vlog: Exploring the Amazon Rainforest",
    videoType: "Video File",
    group: "Travel",
    uploadedDate: "2023-12-01",
    lastUpdated: "2023-12-03",
    uploadedBy: "EcoTravel",
    thumbnailUrl: "",
    isProcessing: false,
    tags: ["rainforest", "travel", "amazon"],
  },
  {
    id: "9",
    title: "Live Stream: Product Launch 2024",
    videoType: "Live Stream",
    group: "Business",
    uploadedDate: "2024-02-14",
    lastUpdated: "2024-02-14",
    uploadedBy: "Tech Corp",
    isProcessing: true,
    tags: ["product", "launch", "2024"],
    thumbnailUrl: "",
  },
  {
    id: "10",
    title: "Recording: Introduction to Data Science",
    videoType: "Recording",
    group: "Education",
    uploadedDate: "2023-05-10",
    lastUpdated: "2023-05-12",
    uploadedBy: "lady@bug.com",
    thumbnailUrl: "",
    isProcessing: false,
    tags: ["data science", "machine learning", "statistics"],
  },
];
